server:
  port: 9090

web:
  upload-path: D:/xiaozhan/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiaozhan?serverTimezone=GMT%2B8&autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

mybatis:
  mapper-locations: classpath:mapper/*.xml
